In [1]:
# test 
import numpy as np
import pandas as pd

## 데이터 로드 & 데이터 구조 및 기초 통계 확인
year = 2020
path = f'./movie_data/{year}/merged_movies_data_{year}.csv'
df = pd.read_csv(path)
#print(df.columns)
display(df.head(2))
print(df.info())
print(df.describe())

,Title,Year,Duration,MPA,Rating,Votes,méta_score,description,Movie Link,writers,...,opening_weekend_Gross,grossWorldWWide,gross_US_Canada,release_date,countries_origin,filming_locations,production_company,awards_content,genres,Languages
0,1. Bad Boys for Life,2020,2h 4m,R,6.5,190K,59.0,Miami detectives Mike Lowrey and Marcus Burnet...,https://www.imdb.com/title/tt1502397/?ref_=sr_i_1,"['Peter Craig', 'Joe Carnahan', 'Chris Bremner']",...,"$62,504,105","$426,505,244","$206,305,244","January 17, 2020",['United States'],"['Yautepec, Morelos, Mexico']","['Columbia Pictures', '2.0 Entertainment', 'Do...","Awards, 3 wins & 15 nominations total","['Buddy Cop', 'Cop Drama', 'Action', 'Comedy',...","['English', 'Spanish']"
1,2. A Quiet Place Part II,2020,1h 37m,PG-13,7.2,302K,71.0,"Following the events at home, the Abbott famil...",https://www.imdb.com/title/tt8332922/?ref_=sr_i_2,"['John Krasinski', 'Bryan Woods', 'Scott Beck']",...,"$47,547,231","$297,372,261","$160,072,261","May 28, 2021",['United States'],"['Buffalo, New York, USA (Studio)']","['Paramount Pictures', 'Platinum Dunes', 'Sund...","Nominated for 1 BAFTA Award, 14 wins & 44 nomi...","['Alien Invasion', 'Monster Horror', 'Supernat...","['English', 'American Sign Language']"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Title                  600 non-null    object
 1   Year                   600 non-null    int64
 2   Duration               598 non-null    object
 3   MPA                    477 non-null    object
 4   Rating                 596 non-null    float64
 5   Votes                  596 non-null    object
 6   méta_score             384 non-null    float64
 7   description            600 non-null    object
 8   Movie Link             600 non-null    object
 9   writers                600 non-null    object
 10  directors              600 non-null    object
 11  stars                  597 non-null    object
 12  budget                 160 non-null    object
 13  opening_weekend_Gross  243 non-null    object
 14  grossWorldWWide        415 non-null    object
 15  gross_US_Canada        268 non-null    object
 16  release_date           600 non-null    object
 17  countries_origin       593 non-null    object
 18  filming_locations      459 non-null    object
 19  production_company     589 non-null    object
 20  awards_content         435 non-null    object
 21  genres                 600 non-null    object
 22  Languages              600 non-null    object
dtypes: float64(2), int64(1), object(20)
memory usage: 107.9+ KB
None
         Year      Rating  méta_score
count   600.0  596.000000  384.000000
mean   2020.0    6.004530   57.815104
std       0.0    1.099242   16.506813
min    2020.0    2.100000    7.000000
25%    2020.0    5.400000   46.000000
50%    2020.0    6.100000   59.000000
75%    2020.0    6.700000   70.000000
max    2020.0    8.800000   97.000000

In [2]:
## 필요 없는 column 제거 (['Rating', 'Votes', 'méta_score', 'description', 'Movie Link', 'writers', 'directors', 'stars', 'opening_weekend_Gross', 'grossWorldWWide', 'gross_US_Canada', 'filming_locations', 'production_company', 'awards_content', 'Languages', 'release_date'])
df = df.drop(['Rating','Votes', 'méta_score', 'description', 'Movie Link', 'writers', 'directors', 'stars', 'opening_weekend_Gross', 'grossWorldWWide', 'gross_US_Canada', 'filming_locations', 'production_company', 'awards_content', 'Languages', 'release_date'], axis=1)
#display(df.head(2))

In [3]:
## YYYY년도 Duration 변환: e.g. 2h 4m -> 124
# 상영 러닝타임 string -> 전체 분(min) 변환
def parse_duration(duration):
    # 상영 시간 값이 NaN 일 때도 변환 가능하게 하기
    if not isinstance(duration, str) or duration.strip() == "":
        return np.nan  # NaN 반환
    hours = 0
    minutes = 0

    if 'h' in duration:
        h_split = duration.split('h')
        hours = int(h_split[0].strip())
        if 'm' in h_split[1]:
            minutes = int(h_split[1].replace('m', '').strip())
    # h(시간)이 0 이어서 생략되었을 때
    elif 'm' in duration:
        minutes = int(duration.replace('m', '').strip())
    
    return hours * 60 + minutes

df['Duration_minute'] = df['Duration'].apply(parse_duration)
# 원래 Duration 컬럼 drop
df = df.drop('Duration', axis=1)
#display(df.head(2))

display(df['Duration_minute'].describe())

# 상영시간 결측치 평균값으로 대체
mean_duration = df['Duration_minute'].mean(skipna=True)
df['Duration_minute'] = df['Duration_minute'].fillna(round(mean_duration))


display(df.info())
display(df.head(2))

count    598.000000
mean     102.909699
std       17.762868
min       45.000000
25%       92.000000
50%      100.000000
75%      112.000000
max      233.000000
Name: Duration_minute, dtype: float64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             600 non-null    object
 1   Year              600 non-null    int64
 2   MPA               477 non-null    object
 3   budget            160 non-null    object
 4   countries_origin  593 non-null    object
 5   genres            600 non-null    object
 6   Duration_minute   600 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 32.9+ KB

None

,Title,Year,MPA,budget,countries_origin,genres,Duration_minute
0,1. Bad Boys for Life,2020,R,"$90,000,000 (estimated)",['United States'],"['Buddy Cop', 'Cop Drama', 'Action', 'Comedy',...",124.0
1,2. A Quiet Place Part II,2020,PG-13,"$61,000,000 (estimated)",['United States'],"['Alien Invasion', 'Monster Horror', 'Supernat...",97.0

In [4]:
## MPA(상영등급) 전처리: 'Not Rated' 및 결측 상영등급 'Unrated'로 변환
df['MPA'] = df['MPA'].fillna('Unrated')
df.loc[df['MPA'] == 'Not Rated', 'MPA'] = 'Unrated'

display(df.info()) # MPA null값 없어짐

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             600 non-null    object
 1   Year              600 non-null    int64
 2   MPA               600 non-null    object
 3   budget            160 non-null    object
 4   countries_origin  593 non-null    object
 5   genres            600 non-null    object
 6   Duration_minute   600 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 32.9+ KB

None

# 1980 - 2025 데이터 합치기 & 전처리

In [6]:
def transform_duration_minutes(df):
    """
    1. 'Duration' 컬럼의 문자열로 되어있는 상영시간을 분석하여,
       'Duration_minute'라는 새 컬럼에 int타입으로 전체 상영시간 분(minute)으로 변환
    2. 'Duration' 컬럼 제거
    3. 결측치(NaN)는 중앙값(median)으로 대체
    """

    # helper function
    def parse_duration(duration):
        if not isinstance(duration, str) or duration.strip() == "":
            return np.nan
        hours, minutes = 0, 0

        if 'h' in duration:
            h_split = duration.split('h')
            hours = int(h_split[0].strip())
            if 'm' in h_split[1]:
                minutes = int(h_split[1].replace('m', '').strip())
        elif 'm' in duration:
            minutes = int(duration.replace('m', '').strip())
        
        return hours * 60 + minutes

    # 1. 변환
    df['Duration_minute'] = df['Duration'].apply(parse_duration)

    # 2. Drop original column
    df.drop(columns=['Duration'], inplace=True)

    # 3. 결측값 -> 중앙값으로 대체
    median_duration = df['Duration_minute'].median()
    df['Duration_minute'] = df['Duration_minute'].fillna(median_duration)

    return df

In [ ]:
## 1980 - 2025 데이터 합치기

# 계속 합칠(업데이트 할) DataFrame 틀 만들기
movie_df = pd.DataFrame(columns=['Title', 'Year', 'MPA', 'budget', 'countries_origin', 'genres', 'Duration_minute'])
#display(movie_df)

years = list(range(1980, 2026))
for year in years:
    path = f'./movie_data/{year}/merged_movies_data_{year}.csv'
    temp_df = pd.read_csv(path)
    
    # 필요 없는 column 제거 (['Rating', 'Votes', 'méta_score', 'description', 'Movie Link', 'writers', 'directors', 'stars', 'opening_weekend_Gross', 'grossWorldWWide', 'gross_US_Canada', 'filming_locations', 'production_company', 'awards_content', 'Languages', 'release_date'])
    temp_df = temp_df.drop(['Rating','Votes', 'méta_score', 'description', 'Movie Link', 'writers', 'directors', 'stars', 'opening_weekend_Gross', 'grossWorldWWide', 'gross_US_Canada', 'filming_locations', 'production_company', 'awards_content', 'Languages', 'release_date'], axis=1)
    
    # Duration 변환: e.g. 2h 4m -> 124
    temp_df = transform_duration_minutes(temp_df)
    
    ## MPA(상영등급) 전처리: 'Not Rated' 및 결측 상영등급 'Unrated'로 변환
    temp_df['MPA'] = temp_df['MPA'].fillna('Unrated')
    temp_df.loc[temp_df['MPA'] == 'Not Rated', 'MPA'] = 'Unrated'
    
    # 기존 dataframe이랑 병합
    movie_df = pd.concat([movie_df,temp_df], axis=0) # 행 기준 병합
    #movie_df.info()
    #print()

C:\Users\Playdata\AppData\Local\Temp\ipykernel_10528\1765392947.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  movie_df = pd.concat([movie_df,temp_df], axis=0) # 행 기준 병합